apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpm
  labels:
    app: tcpm
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tcpm
    spec:
      initContainers:
        - name: sync-tcpm-to-vol
          image: rdavidoff/twitch-channel-points-miner-v2
          command:
            - /bin/bash
            - '-c'
            - |
              set -e -o pipefail
              apt update && apt install -y rsync
              rsync -avh --delete /usr/src/app/TwitchChannelPointsMiner /data
              cp -fv /usr/src/app/requirements.txt /data
              cp -fv /secrets/run.py /data
          volumeMounts:
            - name: tcpm-data
              mountPath: /data
            - name: tcpm-secret
              mountPath: /secrets/run.py
              subPath: run.py
      containers:
        - name: twitch-channel-points-miner-v2
          image: rdavidoff/twitch-channel-points-miner-v2
          ports:
            - containerPort: 5000
              name: http
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 60
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 30
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: tcpm-data
              mountPath: /usr/src/app
      volumes:
        - name: tcpm-data
          persistentVolumeClaim:
            claimName: tcpm-data-vol
        - name: tcpm-secret
          secret:
            secretName: tcpm-secret
