---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - persistent-volume-claim.yaml
  - service.yaml
generators:
  - ksops-generator.yaml
images:
  - name: rdavidoff/twitch-channel-points-miner-v2
    newTag: 1.9.6
