apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcpm-data-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi-retain
