apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controller.yaml
  - csi-driver.yaml
  - node.yaml
  - snapshotter.yaml
images:
  - name: ghcr.io/zebernst/synology-csi:v1.1.2
    newName: ghcr.io/crkochan/synology-csi
    newTag: v1.1.2
