apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  protocol: iscsi
  csi.storage.k8s.io/fstype: ext4
  location: /volume1
reclaimPolicy: Delete
allowVolumeExpansion: true
