apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: sso-client-id
      remoteRef:
        key: argocd
        property: sso-client-id
    - secretKey: sso-client-secret
      remoteRef:
        key: argocd
        property: sso-client-secret
    - secretKey: sso-org
      remoteRef:
        key: argocd
        property: sso-org
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager"
  data:
    - secretKey: cf-api-token
      remoteRef:
        key: cert-manager
        property: cf-api-token
    - secretKey: eab-kid
      remoteRef:
        key: cert-manager
        property: eab-kid
    - secretKey: eab-hmac-key
      remoteRef:
        key: cert-manager
        property: eab-hmac-key
    - secretKey: le-email
      remoteRef:
        key: cert-manager
        property: le-email
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stringreplacesecret
  namespace: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: domain
      remoteRef:
        key: stringreplacesecret
        property: domain
    - secretKey: metallbpooladdress
      remoteRef:
        key: stringreplacesecret
        property: metallbpooladdress
    - secretKey: dsmip
      remoteRef:
        key: stringreplacesecret
        property: dsmip
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: age-private-key
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: keys.txt
      remoteRef:
        key: age-private-key
        property: keys.txt
