kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.0
    helm:
      values: |
        installCRDs: "true"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  data:
    - secretKey: cf-api-token
      remoteRef:
        key: cert-manager
        property: cf-api-token
    - secretKey: eab-kid
      remoteRef:
        key: cert-manager
        property: eab-kid
    - secretKey: eab-hmac-key
      remoteRef:
        key: cert-manager
        property: eab-hmac-key
    - secretKey: le-email
      remoteRef:
        key: cert-manager
        property: le-email
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: cf-api-token
      remoteRef:
        key: cert-manager
        property: cf-api-token
    - secretKey: eab-kid
      remoteRef:
        key: cert-manager
        property: eab-kid
    - secretKey: eab-hmac-key
      remoteRef:
        key: cert-manager
        property: eab-hmac-key
    - secretKey: le-email
      remoteRef:
        key: cert-manager
        property: le-email
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    privateKeySecretRef:
      name: zerossl-prod
    externalAccountBinding:
      keyID: <path:cert-manager#eab-kid>
      keySecretRef:
        name: cert-manager
        key: eab-hmac-key
      keyAlgorithm: HS256
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager
            key: cf-api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager
            key: cf-api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager
            key: cf-api-token
