apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: descheduler
    repoURL: https://kubernetes-sigs.github.io/descheduler
    targetRevision: 0.29.0
    helm:
      values: |
        schedule: '*/15 * * * *'
        suspend: 'false'
        deschedulerPolicyAPIVersion: 'descheduler/v1alpha2'
        deschedulerPolicy:
          profiles:
            - name: default
              pluginConfig:
                - name: DefaultEvictor
                  args:
                    ignorePvcPods: true
                    evictLocalStoragePods: true
                - name: RemoveDuplicates
                - name: RemovePodsHavingTooManyRestarts
                  args:
                    podRestartThreshold: 100
                    includingInitContainers: true
                - name: RemovePodsViolatingNodeTaints
                  args:
                    nodeAffinityType:
                      - requiredDuringSchedulingIgnoredDuringExecution
                - name: RemovePodsViolatingInterPodAntiAffinity
                - name: RemovePodsViolatingTopologySpreadConstraint
                  args:
                    includeSoftConstraints: false
                - name: LowNodeUtilization
                  args:
                    thresholds:
                      cpu: 20
                      memory: 20
                      pods: 20
                    targetThresholds:
                      cpu: 50
                      memory: 50
                      pods: 50
              plugins:
                balance:
                  enabled:
                    - RemoveDuplicates
                    - RemovePodsViolatingNodeAffinity
                    - RemovePodsViolatingTopologySpreadConstraint
                    - LowNodeUtilization
                deschedule:
                  enabled:
                    - RemovePodsHavingTooManyRestarts
                    - RemovePodsViolatingNodeTaints
                    - RemovePodsViolatingNodeAffinity
                    - RemovePodsViolatingInterPodAntiAffinity
          strategies: {}
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
