kind: Namespace
apiVersion: v1
metadata:
  name: eraser
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eraser
  namespace: argocd
spec:
  destination:
    namespace: eraser
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: eraser
    repoURL: https://eraser-dev.github.io/eraser/charts
    targetRevision: 1.2.1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
