kind: Namespace
apiVersion: v1
metadata:
  name: external-dns
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: pihole-password
      remoteRef:
        key: external-dns
        property: pihole-password
    - secretKey: pihole-url
      remoteRef:
        key: external-dns
        property: pihole-url
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.2.0
    helm:
      values: |
        crd:
          create: true
        extraEnvVars:
          - name: EXTERNAL_DNS_PIHOLE_SERVER
            valueFrom:
              secretKeyRef:
                name: external-dns
                key: pihole-url
          - name: EXTERNAL_DNS_PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns
                key: pihole-password
        fullnameOverride: external-dns
        logLevel: info
        policy: upsert-only
        provider: pihole
        registry: noop
        sources:
          - service
          - ingress
          - crd
        txtSuffix: .external-dns
        txtOwnerId: kubernetes
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
