apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.5.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 50Gi
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          ingress:
            ingressClassName: nginx
            enabled: true
            hosts:
              - turing-kube-grafana.<path:stringreplacesecret#domain>
          grafana.ini:
            security:
              angular_support_enabled: false
          persistence:
            enabled: true
            storageClassName: longhorn
            finalizers:
              - kubernetes.io/pvc-protection
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
