kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: homelab
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 57.2.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: ceph-block
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: ceph-block
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          ingress:
            ingressClassName: nginx
            enabled: true
            hosts:
              - turing-kube-grafana.<path:stringreplacesecret#domain>
          grafana.ini:
            security:
              angular_support_enabled: false
          persistence:
            enabled: true
            storageClassName: ceph-block
            finalizers:
              - kubernetes.io/pvc-protection
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
