apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 9.1.37
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
