apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: 1.13.7
    helm:
      valuesObject:
        currentNamespaceOnly: false
        csi:
          enableLiveness: true
          serviceMonitor:
            enabled: true
          readAffinity:
            enabled: true
        monitoring:
          enabled: false
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: 1.13.7
    helm:
      valuesObject:
        operatorNamespace: rook-ceph
        cephClusterSpec:
          storage:
            useAllDevices: false
            deviceFilter: "^nvme0n1"
          crashCollector:
            disable: true
          healthCheck:
            daemonHealth:
              mon:
                disabled: false
                interval: 45s
        ingress:
          dashboard:
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            host:
              name: turing-kube-ceph.<path:stringreplacesecret#domain>
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: false
