kind: Namespace
apiVersion: v1
metadata:
  name: tcpm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tcpm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: tcpm
    server: https://kubernetes.default.svc
  project: homelab
  source:
    path: kustomize/twitch-channel-points-miner-v2
    repoURL: https://github.com/crkochan/argocd-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcpm-http
  namespace: tcpm
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tcpm.<path:stringreplacesecret#domain>
  rules:
    - host: tcpm.<path:stringreplacesecret#domain>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tcpm
                port:
                  name: http
