apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: "apps"
      kind: "Deployment"
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.initContainers[].resources
    - group: "apps"
      kind: "DaemonSet"
      jqPathExpressions:
        - .spec.template.spec.containers[].resources
  project: homelab
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.71.1
    helm:
      valuesObject:
        argocdReleaseOverride: "vm"
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - turing-kube-grafana.<path:stringreplacesecret#domain>
        kubeProxy:
          enabled: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
