---
clusterName: ${clusterName}
talosVersion: v1.5.2
talosImageURL: ${talosImageURL}
kubernetesVersion: v1.28.1
endpoint: https://${clusterVIP}:6443
domain: cluster.local
allowSchedulingOnMasters: true

additionalMachineCertSans:
  - ${node1IP}
  - ${node1Name}.${domainName}
  - ${node2IP}
  - ${node2Name}.${domainName}
  - ${node3IP}
  - ${node3Name}.${domainName}
  - ${node4IP}
  - ${node4Name}.${domainName}

additionalApiServerCertSans:
  - ${clusterName}.${domainName}
  - ${node1IP}
  - ${node1Name}.${domainName}
  - ${node2IP}
  - ${node2Name}.${domainName}
  - ${node3IP}
  - ${node3Name}.${domainName}
  - ${node4IP}
  - ${node4Name}.${domainName}

patches:
  - |-
    machine:
      files:
        - path: /var/etc/nut/upsmon.conf
          op: create
          permissions: 0o600
          content: |-
            MONITOR ${nutName}@${nutServer} 1 ${nutUser} ${nutPassword} slave
            SHUTDOWNCMD "/sbin/poweroff"
      kubelet:
        extraArgs:
          rotate-server-certificates: true
      features:
        kubePrism:
          enabled: true
          port: 7445
    cluster:
      discovery:
        registries:
            kubernetes:
                disabled: false
            service:
              disabled: true

nodes:
  - hostname: ${node1Name}.${domainName}
    ipAddress: ${node1IP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/nut-client
    installDisk: /dev/mmcblk0
    kernelModules:
      - name: rockchip-cpufreq
    controlPlane: true
    nameservers:
      - ${nameServer}
    networkInterfaces:
      - interface: ${node1Interface}
        addresses:
          - ${node1IP}/23
        vip:
          ip: ${clusterVIP}
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
  - hostname: ${node2Name}.${domainName}
    ipAddress: ${node2IP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/nut-client
    installDisk: /dev/mmcblk0
    kernelModules:
      - name: rockchip-cpufreq
    controlPlane: true
    nameservers:
      - ${nameServer}
    networkInterfaces:
      - interface: ${node2Interface}
        addresses:
          - ${node2IP}/23
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
  - hostname: ${node3Name}.${domainName}
    ipAddress: ${node3IP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/nut-client
    installDisk: /dev/mmcblk0
    kernelModules:
      - name: rockchip-cpufreq
    controlPlane: true
    nameservers:
      - ${nameServer}
    networkInterfaces:
      - interface: ${node3Interface}
        addresses:
          - ${node3IP}/23
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
  - hostname: ${node4Name}.${domainName}
    ipAddress: ${node4IP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/nut-client
    installDisk: /dev/mmcblk0
    kernelModules:
      - name: rockchip-cpufreq
    controlPlane: false
    nodeLabels:
      kubernetes.io/role: worker
    nameservers:
      - ${nameServer}
    networkInterfaces:
      - interface: ${node4Interface}
        addresses:
          - ${node4IP}/23
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
